// LES TEXTES PROPRES À DROPLET WEB — ce que l'app n'a pas besoin de dire :
// la souris, le clavier, le navigateur, les appareils liés. Dix langues,
// comme l'app. Les paramètres s'écrivent entre accolades : {nom}.
const Map<String, Map<String, String>> textesWeb = {
  'fr': {
    'aPropos': 'À propos',
    'aProposIndication': 'Disponible, en réunion, au festival…',
    'accueilActus': 'Les actus de vos contacts, pendant 24 heures. Choisissez-en une à gauche, ou publiez la vôtre.',
    'accueilAppels': 'Appelez vos contacts en audio ou en vidéo depuis votre ordinateur, chiffré de bout en bout.',
    'accueilReglages': 'Votre profil, l’apparence, les notifications et les appareils liés. Tout est enregistré aussitôt.',
    'actifMaintenant': 'Actif maintenant',
    'aideTitre': 'Aide',
    'ajouterContact': 'Ajouter un contact',
    'ajouterContactTexte': 'Le pseudo Droplet de la personne. Elle recevra votre demande sur son téléphone.',
    'appareilsLies': 'Appareils liés',
    'appareilsNote': 'Chaque appareil lié a ses propres clés. Votre téléphone peut le retirer à tout moment depuis Réglages › Appareils liés.',
    'appareilsTexte': 'Droplet Web fonctionne même quand votre téléphone est éteint : ce navigateur est un appareil associé à votre compte, avec ses propres clés de chiffrement.',
    'archivesNote': 'Les discussions archivées restent ici, même quand un nouveau message arrive.',
    'aucunTelephone': 'Aucun téléphone lié (démonstration)',
    'centreAide': 'Centre d’aide',
    'cetAppareil': 'Cet appareil',
    'changerFond': 'Changer le fond',
    'chiffrementDetail': 'Messages et appels chiffrés de bout en bout. Touchez pour vérifier.',
    'cliquerInfos': 'Cliquez pour les infos',
    'codeSecuriteTexte': 'Comparez ces chiffres avec ceux affichés chez votre contact. S’ils sont identiques, personne ne s’est glissé entre vous.',
    'conditions': 'Conditions d’utilisation',
    'confidentialite': 'Confidentialité',
    'confirmationsLecture': 'Confirmations de lecture',
    'confirmationsNote': 'Désactivées, vous ne voyez plus les coches de lecture des autres, et ils ne voient plus les vôtres.',
    'connexionEnCours': 'Connexion…',
    'contacts': 'Mes contacts',
    'deconnexion': 'Se déconnecter',
    'deconnexionTexte': 'Ce navigateur oubliera vos discussions et ses clés. Vous pourrez le lier à nouveau avec le code QR.',
    'deconnexionTitre': 'Se déconnecter de ce navigateur ?',
    'discussionPrecedente': 'Discussion précédente',
    'discussionSuivante': 'Discussion suivante',
    'discussionsSous': 'Thème, couleur, taille du texte, fond',
    'effacerJournal': 'Effacer le journal d’appels',
    'emojis': 'Émojis',
    'entreeEnvoie': 'Entrée pour envoyer',
    'entreeEnvoieNote': 'Activé : Entrée envoie, Maj+Entrée va à la ligne. Désactivé : Ctrl+Entrée envoie.',
    'ephemereDesactive': 'Messages éphémères désactivés',
    'essayerDemo': 'Essayer la démonstration',
    'fermer': 'Fermer',
    'horsLigne': 'Hors ligne · les messages partiront au retour du réseau',
    'infosDiscussion': 'Infos de la discussion',
    'lierTelephone': 'Lier mon téléphone',
    'marquerLue': 'Marquer comme lue',
    'marquerNonLue': 'Marquer comme non lue',
    'mediasLiensDocs': 'Médias, liens et documents',
    'messageIntrouvable': 'Message introuvable',
    'messageSupprime': 'Ce message a été supprimé',
    'modeDemo': 'Démonstration · rien ne quitte ce navigateur',
    'nommerAdmin': 'Nommer administrateur',
    'notificationsNavigateur': 'Notifications du navigateur',
    'notificationsNote': 'Les notifications n’apparaissent que lorsque l’onglet Droplet Web n’est pas au premier plan. Le contenu reste chiffré jusqu’à ce navigateur.',
    'notificationsRefusees': 'Bloquées dans le navigateur : autorisez-les dans les réglages du site.',
    'nouvelleLigne': 'Nouvelle ligne',
    'photos': 'Photos',
    'plus': 'Plus',
    'plusMembre': 'Vous ne faites plus partie de ce groupe.',
    'profil': 'Profil',
    'profilSynchro': 'Votre profil est le même sur tous vos appareils.',
    'pseudo': 'Pseudo',
    'pseudoNote': 'C’est le nom que voient vos contacts.',
    'raccourcis': 'Raccourcis clavier',
    'reagir': 'Réagir',
    'recents': 'Récents',
    'rechercherDansDiscussion': 'Rechercher dans la discussion',
    'retirerAdmin': 'Retirer les droits d’administrateur',
    'securite': 'Sécurité',
    'statutsChiffres': 'Vos actus sont chiffrées de bout en bout et disparaissent après 24 heures.',
    'suppressionDiscussion': 'Les messages disparaissent de ce navigateur. Vos autres appareils les gardent.',
    'supprimerMessage': 'Supprimer le message ?',
    'supprimerPourMoi': 'Supprimer pour moi',
    'supprimerPourMoiTexte': 'Le message disparaît de vos appareils seulement.',
    'supprimerPourTous': 'Supprimer pour tout le monde',
    'telechargerFichier': 'Télécharger',
    'telephonePrincipal': 'Téléphone principal',
    'telephoneTexte': 'Garde l’identité du compte et signe les appareils liés',
    'toucheEntree': 'Entrée',
    'toutMarquerLu': 'Tout marquer comme lu',
    'videListe': 'Écrivez à un contact ou créez un groupe : vos discussions s’afficheront ici.',
    'vider': 'Vider',
    'viderDiscussion': 'Vider la discussion',
    'viderTexte': 'Tous les messages de cette discussion seront effacés de ce navigateur.',
    'vocal': 'Message vocal',
    'voirDansDiscussion': 'Voir dans la discussion',
    'vous': 'Vous',
    'vousAvezSupprime': 'Vous avez supprimé ce message',
    'aQuitte': '{nom} a quitté le groupe',
    'aRetire': '{qui} a retiré {nom}',
    'aRenomme': '{qui} a renommé le groupe en « {titre} »',
    'creeLe': 'Groupe créé le {date}',
    'deposerIci': 'Déposez ici pour envoyer à {nom}',
    'envoyerA': 'Envoyer à {nom}',
    'envoyerMessageA': 'Écrire à {nom}',
    'ephemereActive': 'Messages éphémères activés : {duree}',
    'groupesCommun': '{n} groupe(s) en commun',
  },
  'en': {
    'aPropos': 'About',
    'aProposIndication': 'Available, in a meeting, at the festival…',
    'accueilActus': 'Your contacts’ updates, for 24 hours. Pick one on the left, or post your own.',
    'accueilAppels': 'Call your contacts with audio or video from your computer, end-to-end encrypted.',
    'accueilReglages': 'Your profile, appearance, notifications and linked devices. Everything is saved instantly.',
    'actifMaintenant': 'Active now',
    'aideTitre': 'Help',
    'ajouterContact': 'Add a contact',
    'ajouterContactTexte': 'The person’s Droplet username. They’ll get your request on their phone.',
    'appareilsLies': 'Linked devices',
    'appareilsNote': 'Each linked device has its own keys. Your phone can remove it at any time from Settings › Linked devices.',
    'appareilsTexte': 'Droplet Web works even when your phone is off: this browser is a device linked to your account, with its own encryption keys.',
    'archivesNote': 'Archived chats stay here, even when a new message arrives.',
    'aucunTelephone': 'No phone linked (demo)',
    'centreAide': 'Help center',
    'cetAppareil': 'This device',
    'changerFond': 'Change background',
    'chiffrementDetail': 'Messages and calls are end-to-end encrypted. Click to verify.',
    'cliquerInfos': 'Click for info',
    'codeSecuriteTexte': 'Compare these numbers with the ones on your contact’s screen. If they match, no one is in between.',
    'conditions': 'Terms of use',
    'confidentialite': 'Privacy',
    'confirmationsLecture': 'Read receipts',
    'confirmationsNote': 'When off, you won’t see other people’s read receipts, and they won’t see yours.',
    'connexionEnCours': 'Connecting…',
    'contacts': 'My contacts',
    'deconnexion': 'Log out',
    'deconnexionTexte': 'This browser will forget your chats and its keys. You can link it again with the QR code.',
    'deconnexionTitre': 'Log out of this browser?',
    'discussionPrecedente': 'Previous chat',
    'discussionSuivante': 'Next chat',
    'discussionsSous': 'Theme, color, text size, wallpaper',
    'effacerJournal': 'Clear call log',
    'emojis': 'Emoji',
    'entreeEnvoie': 'Enter to send',
    'entreeEnvoieNote': 'On: Enter sends, Shift+Enter adds a line. Off: Ctrl+Enter sends.',
    'ephemereDesactive': 'Disappearing messages turned off',
    'essayerDemo': 'Try the demo',
    'fermer': 'Close',
    'horsLigne': 'Offline · messages will go out when you’re back online',
    'infosDiscussion': 'Chat info',
    'lierTelephone': 'Link my phone',
    'marquerLue': 'Mark as read',
    'marquerNonLue': 'Mark as unread',
    'mediasLiensDocs': 'Media, links and docs',
    'messageIntrouvable': 'Message not found',
    'messageSupprime': 'This message was deleted',
    'modeDemo': 'Demo · nothing leaves this browser',
    'nommerAdmin': 'Make admin',
    'notificationsNavigateur': 'Browser notifications',
    'notificationsNote': 'Notifications only appear when the Droplet Web tab isn’t in front. Content stays encrypted all the way to this browser.',
    'notificationsRefusees': 'Blocked by the browser: allow them in the site settings.',
    'nouvelleLigne': 'New line',
    'photos': 'Photos',
    'plus': 'More',
    'plusMembre': 'You’re no longer a member of this group.',
    'profil': 'Profile',
    'profilSynchro': 'Your profile is the same on all your devices.',
    'pseudo': 'Username',
    'pseudoNote': 'This is the name your contacts see.',
    'raccourcis': 'Keyboard shortcuts',
    'reagir': 'React',
    'recents': 'Recent',
    'rechercherDansDiscussion': 'Search in chat',
    'retirerAdmin': 'Dismiss as admin',
    'securite': 'Security',
    'statutsChiffres': 'Your updates are end-to-end encrypted and disappear after 24 hours.',
    'suppressionDiscussion': 'Messages disappear from this browser. Your other devices keep them.',
    'supprimerMessage': 'Delete message?',
    'supprimerPourMoi': 'Delete for me',
    'supprimerPourMoiTexte': 'The message disappears from your devices only.',
    'supprimerPourTous': 'Delete for everyone',
    'telechargerFichier': 'Download',
    'telephonePrincipal': 'Main phone',
    'telephoneTexte': 'Holds the account identity and signs linked devices',
    'toucheEntree': 'Enter',
    'toutMarquerLu': 'Mark all as read',
    'videListe': 'Message a contact or create a group: your chats will show up here.',
    'vider': 'Clear',
    'viderDiscussion': 'Clear chat',
    'viderTexte': 'All messages in this chat will be erased from this browser.',
    'vocal': 'Voice message',
    'voirDansDiscussion': 'Show in chat',
    'vous': 'You',
    'vousAvezSupprime': 'You deleted this message',
    'aQuitte': '{nom} left the group',
    'aRetire': '{qui} removed {nom}',
    'aRenomme': '{qui} renamed the group to “{titre}”',
    'creeLe': 'Group created on {date}',
    'deposerIci': 'Drop here to send to {nom}',
    'envoyerA': 'Send to {nom}',
    'envoyerMessageA': 'Message {nom}',
    'ephemereActive': 'Disappearing messages on: {duree}',
    'groupesCommun': '{n} group(s) in common',
  },
  'de': {
    'aPropos': 'Info',
    'aProposIndication': 'Verfügbar, im Meeting, auf dem Festival …',
    'accueilActus': 'Die Neuigkeiten deiner Kontakte, 24 Stunden lang. Wähle links eine aus oder teile deine eigene.',
    'accueilAppels': 'Ruf deine Kontakte per Audio oder Video von deinem Computer aus an – Ende-zu-Ende-verschlüsselt.',
    'accueilReglages': 'Dein Profil, Darstellung, Mitteilungen und verknüpfte Geräte. Alles wird sofort gespeichert.',
    'actifMaintenant': 'Jetzt aktiv',
    'aideTitre': 'Hilfe',
    'ajouterContact': 'Kontakt hinzufügen',
    'ajouterContactTexte': 'Der Droplet-Benutzername der Person. Sie erhält deine Anfrage auf ihrem Telefon.',
    'appareilsLies': 'Verknüpfte Geräte',
    'appareilsNote': 'Jedes verknüpfte Gerät hat eigene Schlüssel. Dein Telefon kann es jederzeit unter Einstellungen › Verknüpfte Geräte entfernen.',
    'appareilsTexte': 'Droplet Web funktioniert auch, wenn dein Telefon aus ist: Dieser Browser ist ein mit deinem Konto verknüpftes Gerät mit eigenen Verschlüsselungsschlüsseln.',
    'archivesNote': 'Archivierte Chats bleiben hier, auch wenn eine neue Nachricht eingeht.',
    'aucunTelephone': 'Kein Telefon verknüpft (Demo)',
    'centreAide': 'Hilfe-Center',
    'cetAppareil': 'Dieses Gerät',
    'changerFond': 'Hintergrund ändern',
    'chiffrementDetail': 'Nachrichten und Anrufe sind Ende-zu-Ende-verschlüsselt. Zum Überprüfen klicken.',
    'cliquerInfos': 'Für Infos klicken',
    'codeSecuriteTexte': 'Vergleiche diese Zahlen mit denen auf dem Bildschirm deines Kontakts. Stimmen sie überein, steht niemand zwischen euch.',
    'conditions': 'Nutzungsbedingungen',
    'confidentialite': 'Datenschutz',
    'confirmationsLecture': 'Lesebestätigungen',
    'confirmationsNote': 'Wenn deaktiviert, siehst du keine Lesebestätigungen anderer – und sie sehen deine nicht.',
    'connexionEnCours': 'Verbinden …',
    'contacts': 'Meine Kontakte',
    'deconnexion': 'Abmelden',
    'deconnexionTexte': 'Dieser Browser vergisst deine Chats und seine Schlüssel. Du kannst ihn mit dem QR-Code erneut verknüpfen.',
    'deconnexionTitre': 'Von diesem Browser abmelden?',
    'discussionPrecedente': 'Vorheriger Chat',
    'discussionSuivante': 'Nächster Chat',
    'discussionsSous': 'Design, Farbe, Textgröße, Hintergrund',
    'effacerJournal': 'Anrufliste löschen',
    'emojis': 'Emojis',
    'entreeEnvoie': 'Mit Eingabe senden',
    'entreeEnvoieNote': 'An: Eingabe sendet, Umschalt+Eingabe fügt eine Zeile ein. Aus: Strg+Eingabe sendet.',
    'ephemereDesactive': 'Selbstlöschende Nachrichten deaktiviert',
    'essayerDemo': 'Demo ausprobieren',
    'fermer': 'Schließen',
    'horsLigne': 'Offline · Nachrichten werden gesendet, sobald du wieder online bist',
    'infosDiscussion': 'Chat-Info',
    'lierTelephone': 'Mein Telefon verknüpfen',
    'marquerLue': 'Als gelesen markieren',
    'marquerNonLue': 'Als ungelesen markieren',
    'mediasLiensDocs': 'Medien, Links und Dokumente',
    'messageIntrouvable': 'Nachricht nicht gefunden',
    'messageSupprime': 'Diese Nachricht wurde gelöscht',
    'modeDemo': 'Demo · nichts verlässt diesen Browser',
    'nommerAdmin': 'Zum Admin machen',
    'notificationsNavigateur': 'Browser-Mitteilungen',
    'notificationsNote': 'Mitteilungen erscheinen nur, wenn der Droplet Web-Tab nicht im Vordergrund ist. Der Inhalt bleibt bis zu diesem Browser verschlüsselt.',
    'notificationsRefusees': 'Vom Browser blockiert: Erlaube sie in den Website-Einstellungen.',
    'nouvelleLigne': 'Neue Zeile',
    'photos': 'Fotos',
    'plus': 'Mehr',
    'plusMembre': 'Du bist kein Mitglied dieser Gruppe mehr.',
    'profil': 'Profil',
    'profilSynchro': 'Dein Profil ist auf all deinen Geräten gleich.',
    'pseudo': 'Benutzername',
    'pseudoNote': 'Diesen Namen sehen deine Kontakte.',
    'raccourcis': 'Tastaturkurzbefehle',
    'reagir': 'Reagieren',
    'recents': 'Zuletzt',
    'rechercherDansDiscussion': 'Im Chat suchen',
    'retirerAdmin': 'Als Admin entfernen',
    'securite': 'Sicherheit',
    'statutsChiffres': 'Deine Neuigkeiten sind Ende-zu-Ende-verschlüsselt und verschwinden nach 24 Stunden.',
    'suppressionDiscussion': 'Die Nachrichten verschwinden aus diesem Browser. Deine anderen Geräte behalten sie.',
    'supprimerMessage': 'Nachricht löschen?',
    'supprimerPourMoi': 'Für mich löschen',
    'supprimerPourMoiTexte': 'Die Nachricht verschwindet nur von deinen Geräten.',
    'supprimerPourTous': 'Für alle löschen',
    'telechargerFichier': 'Laden',
    'telephonePrincipal': 'Haupttelefon',
    'telephoneTexte': 'Verwahrt die Kontoidentität und signiert verknüpfte Geräte',
    'toucheEntree': 'Eingabe',
    'toutMarquerLu': 'Alle als gelesen markieren',
    'videListe': 'Schreib einem Kontakt oder erstelle eine Gruppe: Deine Chats erscheinen dann hier.',
    'vider': 'Leeren',
    'viderDiscussion': 'Chat leeren',
    'viderTexte': 'Alle Nachrichten in diesem Chat werden aus diesem Browser gelöscht.',
    'vocal': 'Sprachnachricht',
    'voirDansDiscussion': 'Im Chat anzeigen',
    'vous': 'Du',
    'vousAvezSupprime': 'Du hast diese Nachricht gelöscht',
    'aQuitte': '{nom} hat die Gruppe verlassen',
    'aRetire': '{qui} hat {nom} entfernt',
    'aRenomme': '{qui} hat die Gruppe in „{titre}“ umbenannt',
    'creeLe': 'Gruppe erstellt am {date}',
    'deposerIci': 'Hier ablegen, um an {nom} zu senden',
    'envoyerA': 'An {nom} senden',
    'envoyerMessageA': '{nom} schreiben',
    'ephemereActive': 'Selbstlöschende Nachrichten aktiviert: {duree}',
    'groupesCommun': '{n} gemeinsame Gruppe(n)',
  },
  'es': {
    'aPropos': 'Info.',
    'aProposIndication': 'Disponible, en una reunión, en el festival…',
    'accueilActus': 'Las novedades de tus contactos, durante 24 horas. Elige una a la izquierda o publica la tuya.',
    'accueilAppels': 'Llama a tus contactos por audio o video desde tu computadora, con cifrado de extremo a extremo.',
    'accueilReglages': 'Tu perfil, la apariencia, las notificaciones y los dispositivos vinculados. Todo se guarda al instante.',
    'actifMaintenant': 'Activo ahora',
    'aideTitre': 'Ayuda',
    'ajouterContact': 'Añadir contacto',
    'ajouterContactTexte': 'El nombre de usuario de Droplet de la persona. Recibirá tu solicitud en su teléfono.',
    'appareilsLies': 'Dispositivos vinculados',
    'appareilsNote': 'Cada dispositivo vinculado tiene sus propias claves. Tu teléfono puede eliminarlo en cualquier momento desde Ajustes › Dispositivos vinculados.',
    'appareilsTexte': 'Droplet Web funciona aunque tu teléfono esté apagado: este navegador es un dispositivo vinculado a tu cuenta, con sus propias claves de cifrado.',
    'archivesNote': 'Los chats archivados se quedan aquí, aunque llegue un mensaje nuevo.',
    'aucunTelephone': 'Ningún teléfono vinculado (demo)',
    'centreAide': 'Centro de ayuda',
    'cetAppareil': 'Este dispositivo',
    'changerFond': 'Cambiar fondo',
    'chiffrementDetail': 'Los mensajes y las llamadas están cifrados de extremo a extremo. Haz clic para verificar.',
    'cliquerInfos': 'Haz clic para ver la info.',
    'codeSecuriteTexte': 'Compara estos números con los que aparecen en la pantalla de tu contacto. Si coinciden, nadie se ha interpuesto entre ustedes.',
    'conditions': 'Condiciones de uso',
    'confidentialite': 'Privacidad',
    'confirmationsLecture': 'Confirmaciones de lectura',
    'confirmationsNote': 'Si las desactivas, no verás las confirmaciones de lectura de los demás, y ellos no verán las tuyas.',
    'connexionEnCours': 'Conectando…',
    'contacts': 'Mis contactos',
    'deconnexion': 'Cerrar sesión',
    'deconnexionTexte': 'Este navegador olvidará tus chats y sus claves. Podrás vincularlo de nuevo con el código QR.',
    'deconnexionTitre': '¿Cerrar sesión en este navegador?',
    'discussionPrecedente': 'Chat anterior',
    'discussionSuivante': 'Chat siguiente',
    'discussionsSous': 'Tema, color, tamaño del texto, fondo',
    'effacerJournal': 'Borrar registro de llamadas',
    'emojis': 'Emojis',
    'entreeEnvoie': 'Enviar con Intro',
    'entreeEnvoieNote': 'Activado: Intro envía y Mayús+Intro añade una línea. Desactivado: Ctrl+Intro envía.',
    'ephemereDesactive': 'Mensajes temporales desactivados',
    'essayerDemo': 'Probar la demo',
    'fermer': 'Cerrar',
    'horsLigne': 'Sin conexión · los mensajes se enviarán cuando vuelvas a estar en línea',
    'infosDiscussion': 'Info. del chat',
    'lierTelephone': 'Vincular mi teléfono',
    'marquerLue': 'Marcar como leído',
    'marquerNonLue': 'Marcar como no leído',
    'mediasLiensDocs': 'Archivos, enlaces y documentos',
    'messageIntrouvable': 'No se encontró el mensaje',
    'messageSupprime': 'Se eliminó este mensaje',
    'modeDemo': 'Demo · nada sale de este navegador',
    'nommerAdmin': 'Designar como admin.',
    'notificationsNavigateur': 'Notificaciones del navegador',
    'notificationsNote': 'Las notificaciones solo aparecen cuando la pestaña de Droplet Web no está en primer plano. El contenido sigue cifrado hasta llegar a este navegador.',
    'notificationsRefusees': 'Bloqueadas por el navegador: permítelas en la configuración del sitio.',
    'nouvelleLigne': 'Nueva línea',
    'photos': 'Fotos',
    'plus': 'Más',
    'plusMembre': 'Ya no eres miembro de este grupo.',
    'profil': 'Perfil',
    'profilSynchro': 'Tu perfil es el mismo en todos tus dispositivos.',
    'pseudo': 'Nombre de usuario',
    'pseudoNote': 'Es el nombre que ven tus contactos.',
    'raccourcis': 'Atajos de teclado',
    'reagir': 'Reaccionar',
    'recents': 'Recientes',
    'rechercherDansDiscussion': 'Buscar en el chat',
    'retirerAdmin': 'Descartar como admin.',
    'securite': 'Seguridad',
    'statutsChiffres': 'Tus novedades están cifradas de extremo a extremo y desaparecen después de 24 horas.',
    'suppressionDiscussion': 'Los mensajes desaparecen de este navegador. Tus otros dispositivos los conservan.',
    'supprimerMessage': '¿Eliminar mensaje?',
    'supprimerPourMoi': 'Eliminar para mí',
    'supprimerPourMoiTexte': 'El mensaje desaparece solo de tus dispositivos.',
    'supprimerPourTous': 'Eliminar para todos',
    'telechargerFichier': 'Descargar',
    'telephonePrincipal': 'Teléfono principal',
    'telephoneTexte': 'Guarda la identidad de la cuenta y firma los dispositivos vinculados',
    'toucheEntree': 'Intro',
    'toutMarquerLu': 'Marcar todo como leído',
    'videListe': 'Escribe a un contacto o crea un grupo: tus chats aparecerán aquí.',
    'vider': 'Vaciar',
    'viderDiscussion': 'Vaciar chat',
    'viderTexte': 'Todos los mensajes de este chat se borrarán de este navegador.',
    'vocal': 'Mensaje de voz',
    'voirDansDiscussion': 'Ver en el chat',
    'vous': 'Tú',
    'vousAvezSupprime': 'Eliminaste este mensaje',
    'aQuitte': '{nom} salió del grupo',
    'aRetire': '{qui} eliminó a {nom}',
    'aRenomme': '{qui} cambió el nombre del grupo a «{titre}»',
    'creeLe': 'Grupo creado el {date}',
    'deposerIci': 'Suelta aquí para enviar a {nom}',
    'envoyerA': 'Enviar a {nom}',
    'envoyerMessageA': 'Escribir a {nom}',
    'ephemereActive': 'Mensajes temporales activados: {duree}',
    'groupesCommun': '{n} grupo(s) en común',
  },
  'it': {
    'aPropos': 'Info',
    'aProposIndication': 'Disponibile, in riunione, al festival…',
    'accueilActus': 'Gli aggiornamenti dei tuoi contatti, per 24 ore. Scegline uno a sinistra o pubblica il tuo.',
    'accueilAppels': 'Chiama i tuoi contatti in audio o video dal computer, con crittografia end-to-end.',
    'accueilReglages': 'Il tuo profilo, l’aspetto, le notifiche e i dispositivi collegati. Tutto viene salvato subito.',
    'actifMaintenant': 'Attivo ora',
    'aideTitre': 'Aiuto',
    'ajouterContact': 'Aggiungi contatto',
    'ajouterContactTexte': 'Il nome utente Droplet della persona. Riceverà la tua richiesta sul telefono.',
    'appareilsLies': 'Dispositivi collegati',
    'appareilsNote': 'Ogni dispositivo collegato ha le proprie chiavi. Il tuo telefono può rimuoverlo in qualsiasi momento da Impostazioni › Dispositivi collegati.',
    'appareilsTexte': 'Droplet Web funziona anche quando il telefono è spento: questo browser è un dispositivo collegato al tuo account, con le proprie chiavi di crittografia.',
    'archivesNote': 'Le chat archiviate restano qui, anche quando arriva un nuovo messaggio.',
    'aucunTelephone': 'Nessun telefono collegato (demo)',
    'centreAide': 'Centro assistenza',
    'cetAppareil': 'Questo dispositivo',
    'changerFond': 'Cambia sfondo',
    'chiffrementDetail': 'Messaggi e chiamate sono crittografati end-to-end. Fai clic per verificare.',
    'cliquerInfos': 'Fai clic per le info',
    'codeSecuriteTexte': 'Confronta questi numeri con quelli sullo schermo del tuo contatto. Se coincidono, nessuno si è messo in mezzo.',
    'conditions': 'Termini di utilizzo',
    'confidentialite': 'Privacy',
    'confirmationsLecture': 'Conferme di lettura',
    'confirmationsNote': 'Se disattivate, non vedrai le conferme di lettura degli altri e loro non vedranno le tue.',
    'connexionEnCours': 'Connessione…',
    'contacts': 'I miei contatti',
    'deconnexion': 'Esci',
    'deconnexionTexte': 'Questo browser dimenticherà le tue chat e le sue chiavi. Potrai collegarlo di nuovo con il codice QR.',
    'deconnexionTitre': 'Uscire da questo browser?',
    'discussionPrecedente': 'Chat precedente',
    'discussionSuivante': 'Chat successiva',
    'discussionsSous': 'Tema, colore, dimensione del testo, sfondo',
    'effacerJournal': 'Cancella registro chiamate',
    'emojis': 'Emoji',
    'entreeEnvoie': 'Invio per inviare',
    'entreeEnvoieNote': 'Attivo: Invio invia, Maiusc+Invio va a capo. Disattivo: Ctrl+Invio invia.',
    'ephemereDesactive': 'Messaggi effimeri disattivati',
    'essayerDemo': 'Prova la demo',
    'fermer': 'Chiudi',
    'horsLigne': 'Offline · i messaggi partiranno quando tornerai online',
    'infosDiscussion': 'Info chat',
    'lierTelephone': 'Collega il mio telefono',
    'marquerLue': 'Segna come letta',
    'marquerNonLue': 'Segna come da leggere',
    'mediasLiensDocs': 'Media, link e documenti',
    'messageIntrouvable': 'Messaggio non trovato',
    'messageSupprime': 'Questo messaggio è stato eliminato',
    'modeDemo': 'Demo · nulla esce da questo browser',
    'nommerAdmin': 'Nomina amministratore',
    'notificationsNavigateur': 'Notifiche del browser',
    'notificationsNote': 'Le notifiche appaiono solo quando la scheda di Droplet Web non è in primo piano. Il contenuto resta crittografato fino a questo browser.',
    'notificationsRefusees': 'Bloccate dal browser: consentile nelle impostazioni del sito.',
    'nouvelleLigne': 'Nuova riga',
    'photos': 'Foto',
    'plus': 'Altro',
    'plusMembre': 'Non fai più parte di questo gruppo.',
    'profil': 'Profilo',
    'profilSynchro': 'Il tuo profilo è lo stesso su tutti i tuoi dispositivi.',
    'pseudo': 'Nome utente',
    'pseudoNote': 'È il nome che vedono i tuoi contatti.',
    'raccourcis': 'Scorciatoie da tastiera',
    'reagir': 'Reagisci',
    'recents': 'Recenti',
    'rechercherDansDiscussion': 'Cerca nella chat',
    'retirerAdmin': 'Rimuovi come amministratore',
    'securite': 'Sicurezza',
    'statutsChiffres': 'I tuoi aggiornamenti sono crittografati end-to-end e scompaiono dopo 24 ore.',
    'suppressionDiscussion': 'I messaggi scompaiono da questo browser. Gli altri tuoi dispositivi li conservano.',
    'supprimerMessage': 'Eliminare il messaggio?',
    'supprimerPourMoi': 'Elimina per me',
    'supprimerPourMoiTexte': 'Il messaggio scompare solo dai tuoi dispositivi.',
    'supprimerPourTous': 'Elimina per tutti',
    'telechargerFichier': 'Scarica',
    'telephonePrincipal': 'Telefono principale',
    'telephoneTexte': 'Custodisce l’identità dell’account e firma i dispositivi collegati',
    'toucheEntree': 'Invio',
    'toutMarquerLu': 'Segna tutto come letto',
    'videListe': 'Scrivi a un contatto o crea un gruppo: le tue chat appariranno qui.',
    'vider': 'Svuota',
    'viderDiscussion': 'Svuota chat',
    'viderTexte': 'Tutti i messaggi di questa chat verranno cancellati da questo browser.',
    'vocal': 'Messaggio vocale',
    'voirDansDiscussion': 'Mostra nella chat',
    'vous': 'Tu',
    'vousAvezSupprime': 'Hai eliminato questo messaggio',
    'aQuitte': '{nom} ha abbandonato il gruppo',
    'aRetire': '{qui} ha rimosso {nom}',
    'aRenomme': '{qui} ha rinominato il gruppo in «{titre}»',
    'creeLe': 'Gruppo creato il {date}',
    'deposerIci': 'Rilascia qui per inviare a {nom}',
    'envoyerA': 'Invia a {nom}',
    'envoyerMessageA': 'Scrivi a {nom}',
    'ephemereActive': 'Messaggi effimeri attivati: {duree}',
    'groupesCommun': '{n} gruppo/i in comune',
  },
  'pt': {
    'aPropos': 'Recado',
    'aProposIndication': 'Disponível, em reunião, no festival…',
    'accueilActus': 'As novidades dos seus contatos, por 24 horas. Escolha uma à esquerda ou publique a sua.',
    'accueilAppels': 'Ligue para seus contatos por áudio ou vídeo pelo computador, com criptografia de ponta a ponta.',
    'accueilReglages': 'Seu perfil, a aparência, as notificações e os aparelhos conectados. Tudo é salvo na hora.',
    'actifMaintenant': 'Ativo agora',
    'aideTitre': 'Ajuda',
    'ajouterContact': 'Adicionar contato',
    'ajouterContactTexte': 'O nome de usuário Droplet da pessoa. Ela receberá seu pedido no celular.',
    'appareilsLies': 'Aparelhos conectados',
    'appareilsNote': 'Cada aparelho conectado tem as próprias chaves. Seu celular pode removê-lo a qualquer momento em Configurações › Aparelhos conectados.',
    'appareilsTexte': 'O Droplet Web funciona mesmo com o celular desligado: este navegador é um aparelho conectado à sua conta, com as próprias chaves de criptografia.',
    'archivesNote': 'As conversas arquivadas ficam aqui, mesmo quando chega uma nova mensagem.',
    'aucunTelephone': 'Nenhum celular conectado (demonstração)',
    'centreAide': 'Central de ajuda',
    'cetAppareil': 'Este aparelho',
    'changerFond': 'Mudar papel de parede',
    'chiffrementDetail': 'Mensagens e chamadas protegidas com criptografia de ponta a ponta. Clique para verificar.',
    'cliquerInfos': 'Clique para ver os dados',
    'codeSecuriteTexte': 'Compare estes números com os exibidos na tela do seu contato. Se forem iguais, ninguém se colocou entre vocês.',
    'conditions': 'Termos de uso',
    'confidentialite': 'Privacidade',
    'confirmationsLecture': 'Confirmações de leitura',
    'confirmationsNote': 'Se desativadas, você não verá as confirmações de leitura dos outros, e eles não verão as suas.',
    'connexionEnCours': 'Conectando…',
    'contacts': 'Meus contatos',
    'deconnexion': 'Desconectar',
    'deconnexionTexte': 'Este navegador vai esquecer suas conversas e as chaves dele. Você poderá conectá-lo de novo com o código QR.',
    'deconnexionTitre': 'Desconectar deste navegador?',
    'discussionPrecedente': 'Conversa anterior',
    'discussionSuivante': 'Próxima conversa',
    'discussionsSous': 'Tema, cor, tamanho do texto, papel de parede',
    'effacerJournal': 'Limpar histórico de chamadas',
    'emojis': 'Emojis',
    'entreeEnvoie': 'Enter para enviar',
    'entreeEnvoieNote': 'Ativado: Enter envia, Shift+Enter pula uma linha. Desativado: Ctrl+Enter envia.',
    'ephemereDesactive': 'Mensagens temporárias desativadas',
    'essayerDemo': 'Experimentar a demonstração',
    'fermer': 'Fechar',
    'horsLigne': 'Offline · as mensagens serão enviadas quando você voltar a ficar online',
    'infosDiscussion': 'Dados da conversa',
    'lierTelephone': 'Conectar meu celular',
    'marquerLue': 'Marcar como lida',
    'marquerNonLue': 'Marcar como não lida',
    'mediasLiensDocs': 'Mídia, links e docs',
    'messageIntrouvable': 'Mensagem não encontrada',
    'messageSupprime': 'Esta mensagem foi apagada',
    'modeDemo': 'Demonstração · nada sai deste navegador',
    'nommerAdmin': 'Tornar admin',
    'notificationsNavigateur': 'Notificações do navegador',
    'notificationsNote': 'As notificações só aparecem quando a aba do Droplet Web não está em primeiro plano. O conteúdo permanece criptografado até este navegador.',
    'notificationsRefusees': 'Bloqueadas pelo navegador: permita-as nas configurações do site.',
    'nouvelleLigne': 'Nova linha',
    'photos': 'Fotos',
    'plus': 'Mais',
    'plusMembre': 'Você não faz mais parte deste grupo.',
    'profil': 'Perfil',
    'profilSynchro': 'Seu perfil é o mesmo em todos os seus aparelhos.',
    'pseudo': 'Nome de usuário',
    'pseudoNote': 'É o nome que seus contatos veem.',
    'raccourcis': 'Atalhos de teclado',
    'reagir': 'Reagir',
    'recents': 'Recentes',
    'rechercherDansDiscussion': 'Pesquisar na conversa',
    'retirerAdmin': 'Remover como admin',
    'securite': 'Segurança',
    'statutsChiffres': 'Suas novidades são protegidas com criptografia de ponta a ponta e desaparecem após 24 horas.',
    'suppressionDiscussion': 'As mensagens desaparecem deste navegador. Seus outros aparelhos as mantêm.',
    'supprimerMessage': 'Apagar mensagem?',
    'supprimerPourMoi': 'Apagar para mim',
    'supprimerPourMoiTexte': 'A mensagem desaparece apenas dos seus aparelhos.',
    'supprimerPourTous': 'Apagar para todos',
    'telechargerFichier': 'Baixar',
    'telephonePrincipal': 'Celular principal',
    'telephoneTexte': 'Guarda a identidade da conta e assina os aparelhos conectados',
    'toucheEntree': 'Enter',
    'toutMarquerLu': 'Marcar tudo como lido',
    'videListe': 'Escreva para um contato ou crie um grupo: suas conversas aparecerão aqui.',
    'vider': 'Limpar',
    'viderDiscussion': 'Limpar conversa',
    'viderTexte': 'Todas as mensagens desta conversa serão apagadas deste navegador.',
    'vocal': 'Mensagem de voz',
    'voirDansDiscussion': 'Ver na conversa',
    'vous': 'Você',
    'vousAvezSupprime': 'Você apagou esta mensagem',
    'aQuitte': '{nom} saiu do grupo',
    'aRetire': '{qui} removeu {nom}',
    'aRenomme': '{qui} mudou o nome do grupo para “{titre}”',
    'creeLe': 'Grupo criado em {date}',
    'deposerIci': 'Solte aqui para enviar para {nom}',
    'envoyerA': 'Enviar para {nom}',
    'envoyerMessageA': 'Escrever para {nom}',
    'ephemereActive': 'Mensagens temporárias ativadas: {duree}',
    'groupesCommun': '{n} grupo(s) em comum',
  },
  'ru': {
    'aPropos': 'Сведения',
    'aProposIndication': 'На связи, на встрече, на фестивале…',
    'accueilActus': 'Новости ваших контактов — в течение 24 часов. Выберите слева или опубликуйте свою.',
    'accueilAppels': 'Звоните контактам с компьютера — аудио или видео, со сквозным шифрованием.',
    'accueilReglages': 'Профиль, оформление, уведомления и связанные устройства. Всё сохраняется сразу.',
    'actifMaintenant': 'В сети',
    'aideTitre': 'Помощь',
    'ajouterContact': 'Добавить контакт',
    'ajouterContactTexte': 'Имя пользователя Droplet. Человек получит ваш запрос на телефоне.',
    'appareilsLies': 'Связанные устройства',
    'appareilsNote': 'У каждого связанного устройства свои ключи. Телефон может отвязать его в любой момент в разделе Настройки › Связанные устройства.',
    'appareilsTexte': 'Droplet Web работает, даже когда телефон выключен: этот браузер — устройство, связанное с вашим аккаунтом, со своими ключами шифрования.',
    'archivesNote': 'Архивированные чаты остаются здесь, даже когда приходит новое сообщение.',
    'aucunTelephone': 'Телефон не связан (демо)',
    'centreAide': 'Справочный центр',
    'cetAppareil': 'Это устройство',
    'changerFond': 'Сменить фон',
    'chiffrementDetail': 'Сообщения и звонки защищены сквозным шифрованием. Нажмите, чтобы проверить.',
    'cliquerInfos': 'Нажмите для просмотра данных',
    'codeSecuriteTexte': 'Сравните эти цифры с теми, что на экране у вашего контакта. Если они совпадают, между вами никого нет.',
    'conditions': 'Условия использования',
    'confidentialite': 'Конфиденциальность',
    'confirmationsLecture': 'Отчёты о прочтении',
    'confirmationsNote': 'Если выключить, вы не будете видеть отчёты о прочтении других, а они — ваши.',
    'connexionEnCours': 'Подключение…',
    'contacts': 'Мои контакты',
    'deconnexion': 'Выйти',
    'deconnexionTexte': 'Этот браузер забудет ваши чаты и свои ключи. Вы сможете снова связать его по QR-коду.',
    'deconnexionTitre': 'Выйти в этом браузере?',
    'discussionPrecedente': 'Предыдущий чат',
    'discussionSuivante': 'Следующий чат',
    'discussionsSous': 'Тема, цвет, размер текста, фон',
    'effacerJournal': 'Очистить журнал звонков',
    'emojis': 'Эмодзи',
    'entreeEnvoie': 'Отправка по Enter',
    'entreeEnvoieNote': 'Вкл.: Enter отправляет, Shift+Enter — новая строка. Выкл.: отправка по Ctrl+Enter.',
    'ephemereDesactive': 'Исчезающие сообщения выключены',
    'essayerDemo': 'Попробовать демо',
    'fermer': 'Закрыть',
    'horsLigne': 'Нет сети · сообщения отправятся, когда связь появится',
    'infosDiscussion': 'Данные чата',
    'lierTelephone': 'Связать телефон',
    'marquerLue': 'Отметить как прочитанное',
    'marquerNonLue': 'Отметить как непрочитанное',
    'mediasLiensDocs': 'Медиа, ссылки и документы',
    'messageIntrouvable': 'Сообщение не найдено',
    'messageSupprime': 'Это сообщение удалено',
    'modeDemo': 'Демо · ничто не покидает этот браузер',
    'nommerAdmin': 'Назначить админом',
    'notificationsNavigateur': 'Уведомления браузера',
    'notificationsNote': 'Уведомления появляются, только когда вкладка Droplet Web не на переднем плане. Содержимое остаётся зашифрованным до этого браузера.',
    'notificationsRefusees': 'Заблокированы браузером: разрешите их в настройках сайта.',
    'nouvelleLigne': 'Новая строка',
    'photos': 'Фото',
    'plus': 'Ещё',
    'plusMembre': 'Вы больше не участник этой группы.',
    'profil': 'Профиль',
    'profilSynchro': 'Ваш профиль одинаков на всех ваших устройствах.',
    'pseudo': 'Имя пользователя',
    'pseudoNote': 'Это имя видят ваши контакты.',
    'raccourcis': 'Сочетания клавиш',
    'reagir': 'Реакция',
    'recents': 'Недавние',
    'rechercherDansDiscussion': 'Поиск в чате',
    'retirerAdmin': 'Отозвать права админа',
    'securite': 'Безопасность',
    'statutsChiffres': 'Ваши новости защищены сквозным шифрованием и исчезают через 24 часа.',
    'suppressionDiscussion': 'Сообщения исчезнут из этого браузера. На других ваших устройствах они останутся.',
    'supprimerMessage': 'Удалить сообщение?',
    'supprimerPourMoi': 'Удалить у меня',
    'supprimerPourMoiTexte': 'Сообщение исчезнет только с ваших устройств.',
    'supprimerPourTous': 'Удалить у всех',
    'telechargerFichier': 'Скачать',
    'telephonePrincipal': 'Основной телефон',
    'telephoneTexte': 'Хранит идентификатор аккаунта и подписывает связанные устройства',
    'toucheEntree': 'Enter',
    'toutMarquerLu': 'Отметить все как прочитанные',
    'videListe': 'Напишите контакту или создайте группу — ваши чаты появятся здесь.',
    'vider': 'Очистить',
    'viderDiscussion': 'Очистить чат',
    'viderTexte': 'Все сообщения этого чата будут удалены из этого браузера.',
    'vocal': 'Голосовое сообщение',
    'voirDansDiscussion': 'Показать в чате',
    'vous': 'Вы',
    'vousAvezSupprime': 'Вы удалили это сообщение',
    'aQuitte': '{nom} покидает группу',
    'aRetire': '{qui} удаляет {nom}',
    'aRenomme': '{qui} переименовывает группу в «{titre}»',
    'creeLe': 'Группа создана {date}',
    'deposerIci': 'Перетащите сюда, чтобы отправить: {nom}',
    'envoyerA': 'Отправить: {nom}',
    'envoyerMessageA': 'Написать: {nom}',
    'ephemereActive': 'Исчезающие сообщения включены: {duree}',
    'groupesCommun': 'Общих групп: {n}',
  },
  'zh': {
    'aPropos': '个性签名',
    'aProposIndication': '有空、开会中、在音乐节…',
    'accueilActus': '联系人的动态，保留 24 小时。在左侧选择一条，或发布你自己的动态。',
    'accueilAppels': '在电脑上与联系人进行语音或视频通话，全程端到端加密。',
    'accueilReglages': '你的个人资料、外观、通知和已关联设备。所有更改即时保存。',
    'actifMaintenant': '在线',
    'aideTitre': '帮助',
    'ajouterContact': '添加联系人',
    'ajouterContactTexte': '对方的 Droplet 用户名。对方会在手机上收到你的请求。',
    'appareilsLies': '已关联设备',
    'appareilsNote': '每台已关联设备都有自己的密钥。你的手机可随时在“设置 › 已关联设备”中将其移除。',
    'appareilsTexte': '即使手机关机，Droplet Web 也能使用：此浏览器是与你的账户关联的设备，拥有自己的加密密钥。',
    'archivesNote': '已归档的聊天会留在这里，即使收到新消息也是如此。',
    'aucunTelephone': '未关联手机（演示）',
    'centreAide': '帮助中心',
    'cetAppareil': '此设备',
    'changerFond': '更换背景',
    'chiffrementDetail': '消息和通话已进行端到端加密。点击以验证。',
    'cliquerInfos': '点击查看信息',
    'codeSecuriteTexte': '将这些数字与联系人屏幕上显示的数字进行比对。如果一致，说明没有人介入你们之间。',
    'conditions': '使用条款',
    'confidentialite': '隐私',
    'confirmationsLecture': '已读回执',
    'confirmationsNote': '关闭后，你将看不到他人的已读回执，他人也看不到你的。',
    'connexionEnCours': '正在连接…',
    'contacts': '我的联系人',
    'deconnexion': '退出登录',
    'deconnexionTexte': '此浏览器将清除你的聊天记录及其密钥。你可以通过二维码重新关联。',
    'deconnexionTitre': '要在此浏览器上退出登录吗？',
    'discussionPrecedente': '上一个聊天',
    'discussionSuivante': '下一个聊天',
    'discussionsSous': '主题、颜色、文字大小、背景',
    'effacerJournal': '清除通话记录',
    'emojis': '表情符号',
    'entreeEnvoie': '按回车键发送',
    'entreeEnvoieNote': '开启：回车键发送，Shift+回车键换行。关闭：Ctrl+回车键发送。',
    'ephemereDesactive': '限时消息已关闭',
    'essayerDemo': '试用演示版',
    'fermer': '关闭',
    'horsLigne': '离线 · 网络恢复后将发送消息',
    'infosDiscussion': '聊天信息',
    'lierTelephone': '关联我的手机',
    'marquerLue': '标记为已读',
    'marquerNonLue': '标记为未读',
    'mediasLiensDocs': '媒体、链接和文档',
    'messageIntrouvable': '找不到消息',
    'messageSupprime': '此消息已删除',
    'modeDemo': '演示 · 所有数据均不会离开此浏览器',
    'nommerAdmin': '设为管理员',
    'notificationsNavigateur': '浏览器通知',
    'notificationsNote': '仅当 Droplet Web 标签页不在前台时才会显示通知。内容会一直保持加密，直至到达此浏览器。',
    'notificationsRefusees': '已被浏览器阻止：请在网站设置中允许通知。',
    'nouvelleLigne': '换行',
    'photos': '照片',
    'plus': '更多',
    'plusMembre': '你已不再是此群组的成员。',
    'profil': '个人资料',
    'profilSynchro': '你的个人资料在所有设备上保持一致。',
    'pseudo': '用户名',
    'pseudoNote': '这是联系人看到的名字。',
    'raccourcis': '键盘快捷键',
    'reagir': '回应',
    'recents': '最近',
    'rechercherDansDiscussion': '在聊天中搜索',
    'retirerAdmin': '撤销管理员身份',
    'securite': '安全',
    'statutsChiffres': '你的动态已进行端到端加密，并会在 24 小时后消失。',
    'suppressionDiscussion': '消息将从此浏览器中消失。你的其他设备仍会保留。',
    'supprimerMessage': '要删除消息吗？',
    'supprimerPourMoi': '为我删除',
    'supprimerPourMoiTexte': '消息仅会从你的设备上消失。',
    'supprimerPourTous': '为所有人删除',
    'telechargerFichier': '下载',
    'telephonePrincipal': '主手机',
    'telephoneTexte': '保存账户身份并为已关联设备签名',
    'toucheEntree': '回车键',
    'toutMarquerLu': '全部标记为已读',
    'videListe': '给联系人发消息或创建群组：你的聊天将显示在这里。',
    'vider': '清空',
    'viderDiscussion': '清空聊天',
    'viderTexte': '此聊天中的所有消息都将从此浏览器中清除。',
    'vocal': '语音消息',
    'voirDansDiscussion': '在聊天中查看',
    'vous': '你',
    'vousAvezSupprime': '你删除了此消息',
    'aQuitte': '{nom} 已退出群组',
    'aRetire': '{qui} 已将 {nom} 移出群组',
    'aRenomme': '{qui} 已将群组名称改为“{titre}”',
    'creeLe': '群组创建于 {date}',
    'deposerIci': '拖放到此处以发送给 {nom}',
    'envoyerA': '发送给 {nom}',
    'envoyerMessageA': '给 {nom} 发消息',
    'ephemereActive': '限时消息已开启：{duree}',
    'groupesCommun': '{n} 个共同群组',
  },
  'ar': {
    'aPropos': 'الحالة',
    'aProposIndication': 'متاح، في اجتماع، في المهرجان…',
    'accueilActus': 'تحديثات جهات اتصالك لمدة 24 ساعة. اختر واحدًا من القائمة، أو انشر تحديثك.',
    'accueilAppels': 'اتصل بجهات اتصالك صوتيًا أو بالفيديو من الكمبيوتر، مع تشفير تام بين الطرفين.',
    'accueilReglages': 'ملفك الشخصي والمظهر والإشعارات والأجهزة المرتبطة. يُحفظ كل شيء فورًا.',
    'actifMaintenant': 'نشط الآن',
    'aideTitre': 'المساعدة',
    'ajouterContact': 'إضافة جهة اتصال',
    'ajouterContactTexte': 'اسم مستخدم الشخص على Droplet. سيتلقى طلبك على هاتفه.',
    'appareilsLies': 'الأجهزة المرتبطة',
    'appareilsNote': 'لكل جهاز مرتبط مفاتيحه الخاصة. يمكن لهاتفك إزالته في أي وقت من الإعدادات › الأجهزة المرتبطة.',
    'appareilsTexte': 'يعمل Droplet Web حتى عندما يكون هاتفك مغلقًا: هذا المتصفح جهاز مرتبط بحسابك، وله مفاتيح التشفير الخاصة به.',
    'archivesNote': 'تبقى الدردشات المؤرشفة هنا، حتى عند وصول رسالة جديدة.',
    'aucunTelephone': 'لا يوجد هاتف مرتبط (عرض توضيحي)',
    'centreAide': 'مركز المساعدة',
    'cetAppareil': 'هذا الجهاز',
    'changerFond': 'تغيير الخلفية',
    'chiffrementDetail': 'الرسائل والمكالمات مشفرة تمامًا بين الطرفين. انقر للتحقق.',
    'cliquerInfos': 'انقر لعرض المعلومات',
    'codeSecuriteTexte': 'قارن هذه الأرقام بتلك الظاهرة على شاشة جهة اتصالك. إذا تطابقت، فلا أحد يتوسط بينكما.',
    'conditions': 'شروط الاستخدام',
    'confidentialite': 'الخصوصية',
    'confirmationsLecture': 'إشعارات القراءة',
    'confirmationsNote': 'عند إيقافها، لن ترى إشعارات القراءة من الآخرين، ولن يروا إشعاراتك.',
    'connexionEnCours': 'جارٍ الاتصال…',
    'contacts': 'جهات اتصالي',
    'deconnexion': 'تسجيل الخروج',
    'deconnexionTexte': 'سينسى هذا المتصفح دردشاتك ومفاتيحه. يمكنك ربطه مجددًا باستخدام رمز QR.',
    'deconnexionTitre': 'هل تريد تسجيل الخروج من هذا المتصفح؟',
    'discussionPrecedente': 'الدردشة السابقة',
    'discussionSuivante': 'الدردشة التالية',
    'discussionsSous': 'السمة، اللون، حجم النص، الخلفية',
    'effacerJournal': 'مسح سجل المكالمات',
    'emojis': 'الرموز التعبيرية',
    'entreeEnvoie': 'الإرسال بمفتاح Enter',
    'entreeEnvoieNote': 'عند التشغيل: Enter يرسل، وShift+Enter يضيف سطرًا. عند الإيقاف: Ctrl+Enter يرسل.',
    'ephemereDesactive': 'تم إيقاف الرسائل المؤقتة',
    'essayerDemo': 'تجربة العرض التوضيحي',
    'fermer': 'إغلاق',
    'horsLigne': 'غير متصل · ستُرسل الرسائل عند عودة الاتصال',
    'infosDiscussion': 'معلومات الدردشة',
    'lierTelephone': 'ربط هاتفي',
    'marquerLue': 'تعليم كمقروءة',
    'marquerNonLue': 'تعليم كغير مقروءة',
    'mediasLiensDocs': 'الوسائط والروابط والمستندات',
    'messageIntrouvable': 'لم يتم العثور على الرسالة',
    'messageSupprime': 'تم حذف هذه الرسالة',
    'modeDemo': 'عرض توضيحي · لا شيء يغادر هذا المتصفح',
    'nommerAdmin': 'تعيين كمشرف',
    'notificationsNavigateur': 'إشعارات المتصفح',
    'notificationsNote': 'لا تظهر الإشعارات إلا عندما لا تكون علامة تبويب Droplet Web في الواجهة. يبقى المحتوى مشفرًا حتى يصل إلى هذا المتصفح.',
    'notificationsRefusees': 'محظورة من المتصفح: اسمح بها في إعدادات الموقع.',
    'nouvelleLigne': 'سطر جديد',
    'photos': 'الصور',
    'plus': 'المزيد',
    'plusMembre': 'لم تعد عضوًا في هذه المجموعة.',
    'profil': 'الملف الشخصي',
    'profilSynchro': 'ملفك الشخصي هو نفسه على جميع أجهزتك.',
    'pseudo': 'اسم المستخدم',
    'pseudoNote': 'هذا هو الاسم الذي تراه جهات اتصالك.',
    'raccourcis': 'اختصارات لوحة المفاتيح',
    'reagir': 'تفاعل',
    'recents': 'الأحدث',
    'rechercherDansDiscussion': 'البحث في الدردشة',
    'retirerAdmin': 'إلغاء الإشراف',
    'securite': 'الأمان',
    'statutsChiffres': 'تحديثاتك مشفرة تمامًا بين الطرفين وتختفي بعد 24 ساعة.',
    'suppressionDiscussion': 'تختفي الرسائل من هذا المتصفح. وتحتفظ بها أجهزتك الأخرى.',
    'supprimerMessage': 'هل تريد حذف الرسالة؟',
    'supprimerPourMoi': 'حذف لديّ',
    'supprimerPourMoiTexte': 'تختفي الرسالة من أجهزتك فقط.',
    'supprimerPourTous': 'حذف لدى الجميع',
    'telechargerFichier': 'تنزيل',
    'telephonePrincipal': 'الهاتف الرئيسي',
    'telephoneTexte': 'يحتفظ بهوية الحساب ويوقّع الأجهزة المرتبطة',
    'toucheEntree': 'Enter',
    'toutMarquerLu': 'تعليم الكل كمقروء',
    'videListe': 'راسل جهة اتصال أو أنشئ مجموعة: ستظهر دردشاتك هنا.',
    'vider': 'مسح',
    'viderDiscussion': 'مسح الدردشة',
    'viderTexte': 'ستُمحى جميع رسائل هذه الدردشة من هذا المتصفح.',
    'vocal': 'رسالة صوتية',
    'voirDansDiscussion': 'عرض في الدردشة',
    'vous': 'أنت',
    'vousAvezSupprime': 'لقد حذفت هذه الرسالة',
    'aQuitte': 'غادر {nom} المجموعة',
    'aRetire': 'أزال {qui} {nom}',
    'aRenomme': 'غيّر {qui} اسم المجموعة إلى «{titre}»',
    'creeLe': 'أُنشئت المجموعة في {date}',
    'deposerIci': 'أفلت هنا للإرسال إلى {nom}',
    'envoyerA': 'إرسال إلى {nom}',
    'envoyerMessageA': 'مراسلة {nom}',
    'ephemereActive': 'تم تشغيل الرسائل المؤقتة: {duree}',
    'groupesCommun': 'المجموعات المشتركة: {n}',
  },
  'hi': {
    'aPropos': 'परिचय',
    'aProposIndication': 'उपलब्ध, मीटिंग में, फ़ेस्टिवल में…',
    'accueilActus': 'आपके संपर्कों के अपडेट, 24 घंटे के लिए। बाईं ओर से कोई एक चुनें, या अपना अपडेट पोस्ट करें।',
    'accueilAppels': 'अपने कंप्यूटर से संपर्कों को ऑडियो या वीडियो कॉल करें, एंड-टू-एंड एन्क्रिप्टेड।',
    'accueilReglages': 'आपकी प्रोफ़ाइल, रूप-रंग, सूचनाएँ और लिंक किए गए डिवाइस। सब कुछ तुरंत सेव हो जाता है।',
    'actifMaintenant': 'अभी सक्रिय',
    'aideTitre': 'सहायता',
    'ajouterContact': 'संपर्क जोड़ें',
    'ajouterContactTexte': 'व्यक्ति का Droplet यूज़रनेम। उन्हें आपका अनुरोध अपने फ़ोन पर मिलेगा।',
    'appareilsLies': 'लिंक किए गए डिवाइस',
    'appareilsNote': 'हर लिंक किए गए डिवाइस की अपनी कुंजियाँ होती हैं। आपका फ़ोन इसे कभी भी सेटिंग्स › लिंक किए गए डिवाइस से हटा सकता है।',
    'appareilsTexte': 'Droplet Web आपका फ़ोन बंद होने पर भी काम करता है: यह ब्राउज़र आपके अकाउंट से लिंक किया गया डिवाइस है, जिसकी अपनी एन्क्रिप्शन कुंजियाँ हैं।',
    'archivesNote': 'संग्रहित चैट यहीं रहती हैं, नया मैसेज आने पर भी।',
    'aucunTelephone': 'कोई फ़ोन लिंक नहीं है (डेमो)',
    'centreAide': 'सहायता केंद्र',
    'cetAppareil': 'यह डिवाइस',
    'changerFond': 'बैकग्राउंड बदलें',
    'chiffrementDetail': 'मैसेज और कॉल एंड-टू-एंड एन्क्रिप्टेड हैं। सत्यापित करने के लिए क्लिक करें।',
    'cliquerInfos': 'जानकारी के लिए क्लिक करें',
    'codeSecuriteTexte': 'इन नंबरों की तुलना अपने संपर्क की स्क्रीन पर दिख रहे नंबरों से करें। अगर ये मेल खाते हैं, तो आपके बीच कोई नहीं है।',
    'conditions': 'उपयोग की शर्तें',
    'confidentialite': 'गोपनीयता',
    'confirmationsLecture': 'रीड रिसीट',
    'confirmationsNote': 'बंद होने पर, आप दूसरों की रीड रिसीट नहीं देख पाएँगे, और वे आपकी नहीं देख पाएँगे।',
    'connexionEnCours': 'कनेक्ट हो रहा है…',
    'contacts': 'मेरे संपर्क',
    'deconnexion': 'लॉग आउट करें',
    'deconnexionTexte': 'यह ब्राउज़र आपकी चैट और अपनी कुंजियाँ भूल जाएगा। आप इसे QR कोड से फिर से लिंक कर सकते हैं।',
    'deconnexionTitre': 'इस ब्राउज़र से लॉग आउट करें?',
    'discussionPrecedente': 'पिछली चैट',
    'discussionSuivante': 'अगली चैट',
    'discussionsSous': 'थीम, रंग, टेक्स्ट का आकार, बैकग्राउंड',
    'effacerJournal': 'कॉल लॉग साफ़ करें',
    'emojis': 'इमोजी',
    'entreeEnvoie': 'भेजने के लिए Enter',
    'entreeEnvoieNote': 'चालू: Enter से भेजें, Shift+Enter से नई लाइन। बंद: Ctrl+Enter से भेजें।',
    'ephemereDesactive': 'गायब होने वाले मैसेज बंद हैं',
    'essayerDemo': 'डेमो आज़माएँ',
    'fermer': 'बंद करें',
    'horsLigne': 'ऑफ़लाइन · नेटवर्क वापस आने पर मैसेज भेजे जाएँगे',
    'infosDiscussion': 'चैट की जानकारी',
    'lierTelephone': 'मेरा फ़ोन लिंक करें',
    'marquerLue': 'पढ़ा हुआ मार्क करें',
    'marquerNonLue': 'अपठित मार्क करें',
    'mediasLiensDocs': 'मीडिया, लिंक और डॉक्यूमेंट',
    'messageIntrouvable': 'मैसेज नहीं मिला',
    'messageSupprime': 'यह मैसेज डिलीट कर दिया गया',
    'modeDemo': 'डेमो · कुछ भी इस ब्राउज़र से बाहर नहीं जाता',
    'nommerAdmin': 'एडमिन बनाएँ',
    'notificationsNavigateur': 'ब्राउज़र सूचनाएँ',
    'notificationsNote': 'सूचनाएँ तभी दिखती हैं जब Droplet Web टैब सामने न हो। कंटेंट इस ब्राउज़र तक एन्क्रिप्टेड रहता है।',
    'notificationsRefusees': 'ब्राउज़र ने ब्लॉक कर दिया है: साइट सेटिंग्स में इन्हें अनुमति दें।',
    'nouvelleLigne': 'नई लाइन',
    'photos': 'फ़ोटो',
    'plus': 'और',
    'plusMembre': 'अब आप इस ग्रुप के सदस्य नहीं हैं।',
    'profil': 'प्रोफ़ाइल',
    'profilSynchro': 'आपकी प्रोफ़ाइल आपके सभी डिवाइस पर एक जैसी है।',
    'pseudo': 'यूज़रनेम',
    'pseudoNote': 'आपके संपर्क यही नाम देखते हैं।',
    'raccourcis': 'कीबोर्ड शॉर्टकट',
    'reagir': 'प्रतिक्रिया दें',
    'recents': 'हाल ही के',
    'rechercherDansDiscussion': 'चैट में खोजें',
    'retirerAdmin': 'एडमिन से हटाएँ',
    'securite': 'सुरक्षा',
    'statutsChiffres': 'आपके अपडेट एंड-टू-एंड एन्क्रिप्टेड हैं और 24 घंटे बाद गायब हो जाते हैं।',
    'suppressionDiscussion': 'मैसेज इस ब्राउज़र से गायब हो जाएँगे। आपके दूसरे डिवाइस पर ये बने रहेंगे।',
    'supprimerMessage': 'मैसेज डिलीट करें?',
    'supprimerPourMoi': 'मेरे लिए डिलीट करें',
    'supprimerPourMoiTexte': 'मैसेज केवल आपके डिवाइस से गायब होगा।',
    'supprimerPourTous': 'सभी के लिए डिलीट करें',
    'telechargerFichier': 'डाउनलोड करें',
    'telephonePrincipal': 'मुख्य फ़ोन',
    'telephoneTexte': 'अकाउंट की पहचान रखता है और लिंक किए गए डिवाइस को साइन करता है',
    'toucheEntree': 'Enter',
    'toutMarquerLu': 'सभी को पढ़ा हुआ मार्क करें',
    'videListe': 'किसी संपर्क को मैसेज करें या ग्रुप बनाएँ: आपकी चैट यहाँ दिखेंगी।',
    'vider': 'साफ़ करें',
    'viderDiscussion': 'चैट साफ़ करें',
    'viderTexte': 'इस चैट के सभी मैसेज इस ब्राउज़र से मिटा दिए जाएँगे।',
    'vocal': 'वॉइस मैसेज',
    'voirDansDiscussion': 'चैट में दिखाएँ',
    'vous': 'आप',
    'vousAvezSupprime': 'आपने यह मैसेज डिलीट किया',
    'aQuitte': '{nom} ने ग्रुप छोड़ दिया',
    'aRetire': '{qui} ने {nom} को हटाया',
    'aRenomme': '{qui} ने ग्रुप का नाम बदलकर “{titre}” किया',
    'creeLe': 'ग्रुप {date} को बनाया गया',
    'deposerIci': '{nom} को भेजने के लिए यहाँ छोड़ें',
    'envoyerA': '{nom} को भेजें',
    'envoyerMessageA': '{nom} को मैसेज करें',
    'ephemereActive': 'गायब होने वाले मैसेज चालू: {duree}',
    'groupesCommun': '{n} कॉमन ग्रुप',
  },
};
